pipeline:
  identifier: Build_Sadat_Ahmed_jhttp_1783343154869
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: ubuntu-latest
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      - step:
                          type: Run
                          name: Build Java App
                          identifier: Build_Java_App
                          spec:
                            connectorRef: dockerhub_connector
                            image: maven:3.8-jdk-11
                            shell: Sh
                            command: |-
                              mvn clean package dependency:copy-dependencies

                      - step:
                          type: Run
                          name: Run Unit Tests
                          identifier: Run_Unit_Tests
                          spec:
                            connectorRef: dockerhub_connector
                            image: maven:3.8-jdk-11
                            shell: Sh
                            command: |-
                              mvn test
                            reports:
                              type: JUnit
                              spec:
                                paths:
                                  - target/surefire-reports/*.xml
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhub_connector
                    repo: sadatahmed93/jhttp
                    tags:
                      - <+pipeline.sequenceId>
  properties:
    ci:
      codebase:
        connectorRef: github_connector
        build: <+input>
